In [1]:
import numpy as np

# Example sentence embeddings (7 words, embedding dim = 4)
X = np.array([
    [0.1, 0.3, 0.5, 0.2],  # What
    [0.2, 0.4, 0.1, 0.7],  # are
    [0.6, 0.9, 0.3, 0.1],  # the
    [0.8, 0.2, 0.5, 0.4],  # symptoms
    [0.3, 0.7, 0.8, 0.2],  # of
    [0.9, 0.1, 0.4, 0.6],  # diabetes
    [0.2, 0.5, 0.3, 0.9]   # ?
])

# Initialize weight matrices
d_model = X.shape[1]

Wq = np.random.rand(d_model, d_model)
Wk = np.random.rand(d_model, d_model)
Wv = np.random.rand(d_model, d_model)

# Compute Q, K, V
Q = X @ Wq
K = X @ Wk
V = X @ Wv

# Scaled Dot-Product Attention
dk = K.shape[1]

scores = (Q @ K.T) / np.sqrt(dk)

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

# Final output
output = attention_weights @ V

print("Attention Weights:\n", attention_weights)
print("\nOutput:\n", output)

Attention Weights:
 [[0.07683876 0.10757341 0.15442987 0.15973338 0.1589284  0.17988687
  0.1626093 ]
 [0.05795928 0.09238391 0.16098565 0.16173436 0.16920933 0.18908613
  0.16864134]
 [0.04625693 0.08412416 0.15729821 0.16753392 0.1644784  0.20705101
  0.17325738]
 [0.04672738 0.0818463  0.16380373 0.16335723 0.17561544 0.19678807
  0.17186185]
 [0.04477587 0.08266319 0.15672836 0.16843411 0.16432556 0.20958753
  0.17348538]
 [0.04259372 0.07721183 0.16669231 0.16255381 0.18082067 0.19719148
  0.17293619]
 [0.04181139 0.07806931 0.16296509 0.16515126 0.17401106 0.2038847
  0.17410719]]

Output:
 [[0.98471298 1.17570325 0.78681291 1.17724565]
 [0.99781393 1.18964623 0.79636732 1.19500944]
 [1.01038132 1.19979214 0.80375703 1.20669291]
 [1.0069829  1.19856819 0.8031553  1.20681364]
 [1.0122531  1.20117146 0.8049812  1.20853962]
 [1.00953276 1.20166902 0.80551333 1.21127314]
 [1.01200071 1.20283371 0.8061215  1.21169288]]
